import{createHash,randomBytes}from'node:crypto';import{DynamoDBClient}from'@aws-sdk/client-dynamodb';import{DynamoDBDocumentClient,GetCommand,PutCommand,QueryCommand,DeleteCommand,UpdateCommand}from'@aws-sdk/lib-dynamodb';import{store}from'./store';
const table=process.env.AUTOVISION_TABLE,db=DynamoDBDocumentClient.from(new DynamoDBClient({endpoint:process.env.AUTOVISION_DYNAMODB_ENDPOINT}));type Key={tenantId:string;label:string;hash:string;createdAt:string};const memory=new Map<string,Key>(),usage=new Map<string,number>();export const fingerprint=(key:string)=>createHash('sha256').update(key).digest('hex');
export async function createKey(tenantId:string,label:string){const raw='av_'+randomBytes(32).toString('hex'),v={tenantId,label,hash:fingerprint(raw),createdAt:new Date().toISOString()};await store.organizationById(tenantId);if(table){await db.send(new PutCommand({TableName:table,Item:{pk:'ORG#'+tenantId,sk:'KEY#'+v.hash,...v}}));await db.send(new PutCommand({TableName:table,Item:{pk:'APIKEY#'+v.hash,sk:'KEY',...v}}))}else memory.set(v.hash,v);return{key:raw,...v}}
export async function authenticateKey(header:string|null){const raw=header?.replace(/^Bearer /,'')??'';if(!/^av_[a-f0-9]{64}$/.test(raw))return null;const hash=fingerprint(raw);if(table){const r=await db.send(new GetCommand({TableName:table,Key:{pk:'APIKEY#'+hash,sk:'KEY'},ConsistentRead:true}));return(r.Item as Key)??null}return memory.get(hash)??null}
export async function listKeys(tenantId:string){if(table){const r=await db.send(new QueryCommand({TableName:table,KeyConditionExpression:'pk=:pk AND begins_with(sk,:prefix)',ExpressionAttributeValues:{':pk':'ORG#'+tenantId,':prefix':'KEY#'}}));return(r.Items??[]).map(v=>({hash:v.hash,label:v.label,createdAt:v.createdAt}))}return[...memory.values()].filter(v=>v.tenantId===tenantId).map(v=>({hash:v.hash,label:v.label,createdAt:v.createdAt}))}
export async function revokeKey(tenantId:string,hash:string){if(table){const r=await db.send(new GetCommand({TableName:table,Key:{pk:'APIKEY#'+hash,sk:'KEY'},ConsistentRead:true}));if(r.Item?.tenantId!==tenantId)return false;await db.send(new DeleteCommand({TableName:table,Key:{pk:'APIKEY#'+hash,sk:'KEY'}}));await db.send(new DeleteCommand({TableName:table,Key:{pk:'ORG#'+tenantId,sk:'KEY#'+hash}}));return true}if(memory.get(hash)?.tenantId!==tenantId)return false;return memory.delete(hash)}
export async function consume(tenantId:string){const subscription=await store.activeSubscriptionForOrg(tenantId);const limit=process.env.AUTOVISION_DEPLOYMENT_MODE==='on-premise'?1000000000:subscription?.productId==='scale'?100000:subscription?.productId==='starter'?10000:1000;const month=new Date().toISOString().slice(0,7);if(table){try{await db.send(new UpdateCommand({TableName:table,Key:{pk:'ORG#'+tenantId,sk:'USAGE#'+month},UpdateExpression:'ADD #count :one',ConditionExpression:'attribute_not_exists(#count) OR #count < :limit',ExpressionAttributeNames:{'#count':'count'},ExpressionAttributeValues:{':one':1,':limit':limit}}));return true}catch(e){if(e instanceof Error&&e.name==='ConditionalCheckFailedException')return false;throw e}}const k=tenantId+month,n=usage.get(k)??0;if(n>=limit)return false;usage.set(k,n+1);return true}


export async function usageFor(tenantId:string){const s=await store.activeSubscriptionForOrg(tenantId),month=new Date().toISOString().slice(0,7);const limit=s?.productId==='scale'?100000:s?.productId==='starter'?10000:1000;let count=usage.get(tenantId+month)??0;if(table){const r=await db.send(new GetCommand({TableName:table,Key:{pk:'ORG#'+tenantId,sk:'USAGE#'+month},ConsistentRead:true}));count=Number(r.Item?.count??0)}return{month,count,limit,plan:s?.productId??'dev'}}

