import Link from 'next/link';
import PublicShell from './public-shell';
import PublicDemo from './public-demo';
import VisionScene from './vision-scene';
export const dynamic='force-dynamic';
export const metadata={title:'AutoVision — Vision for robots, drones and homes',description:'Give your application a way to see. Image and sampled-video observations for robotics, drones, connected homes and AI agents through one API.'};
const worlds=[
  {id:'robotics',icon:'◎',category:'01 / ROBOTICS',title:'Eyes for your next machine.',text:'Bring visual observations into inspection and robotics workflows. Your controller owns movement, decisions and safety.',href:'/docs/mcp',link:'Build a visual workflow ↗'},
  {id:'drones',icon:'⌁',category:'02 / DRONES',title:'A new perspective.',text:'Send sampled aerial frames into monitoring and inspection workflows. Bring your capture adapter; AutoVision does not pilot aircraft.',href:'/api-reference',link:'Explore frame analysis ↗'},
  {id:'homes',icon:'⌂',category:'03 / CONNECTED HOMES',title:'More context. Less guesswork.',text:'Turn authorized camera images into useful event evidence. SmartDetector brings that visual layer into a personalized device and event console.',href:'https://smartdetector.com',link:'Meet SmartDetector ↗'},
];
export default function Page(){
 return <PublicShell><main className="av-main">
  <section className="av-hero"><div><span className="av-kicker">A VISUAL LAYER FOR THE WORLD YOU BUILD</span><h1>Give your machines<br/>a way to <em>see.</em></h1><p>Robots. Drones. Connected homes. Turn images and sampled video into observations your software can use—with one API for applications and AI agents.</p><div className="av-actions"><a href="#demo" className="av-button">Try AutoVision ↓</a><Link href="/api-reference" className="av-button-secondary">Build with the API ↗</Link></div><div className="av-hero-proof"><span>OpenCV measurements</span><span>Optional AI context</span><span>API + MCP</span></div></div>
  <div className="av-vision-stage" aria-label="Illustrative visual observation pipeline"><div className="av-stage-orbit">◎</div><div className="av-stage-input">CAMERAS · FRAMES · CLIPS</div><div className="av-stage-target"><span>Visual evidence</span><strong>Observe.<br/>Understand.<br/>Build.</strong></div><div className="av-stage-caption">IMAGE → OBSERVATION → YOUR NEXT STEP</div></div></section>
  <section className="av-worlds" aria-labelledby="worlds-title"><span className="av-kicker">ONE PLATFORM. MANY PERSPECTIVES.</span><h2 id="worlds-title">What will you give vision to?</h2><div className="av-world-grid">{worlds.map(world=><article className={'av-world-card av-world-'+world.id} key={world.id}><div className="av-world-visual" aria-hidden="true"><VisionScene kind={world.id}/></div><div className="av-world-copy"><span>{world.category}</span><h3>{world.title}</h3><p>{world.text}</p><Link href={world.href}>{world.link}</Link></div></article>)}</div><p className="av-fine">Illustrative applications, not certified autonomous navigation or life-safety systems. Device connectivity and physical actions belong to your application.</p></section>
  <PublicDemo/>
  <section className="av-build"><span className="av-kicker">PERCEPTION, WITHOUT REBUILDING YOUR PRODUCT</span><h2>From pixels to possibilities.</h2><div className="av-feature-grid"><article><span>OBSERVE</span><h3>Useful visual evidence.</h3><p>Motion measurements, pedestrian boxes and timestamps. Add optional Bedrock scene context and advisory object grounding, kept distinct from measured results.</p><Link href="/api-reference">See the response contract ↗</Link></article><article><span>CONNECT</span><h3>Your application. Your logic.</h3><p>Use organization-scoped keys for images and timed frame batches. Stateless face measurements leave consent, names and matching in your application.</p><Link href="/api-reference#integration">See the integration pattern ↗</Link></article><article><span>BUILD</span><h3>Give agents a visual tool.</h3><p>Bring image analysis into a larger workflow through MCP. Your agent uses the evidence to choose its next step, with the permissions and human controls you provide.</p><Link href="/docs/mcp">Connect an agent ↗</Link></article></div></section>
  <section className="av-network"><div><span className="av-kicker">THE ROAD AHEAD / PLANNED</span><h2>A home that sees together.</h2><p>Our home-network vision brings cameras, household devices and robots into a shared observation layer. AutoVision provides perception. SmartDetector brings devices and events together. Future integrations could turn those observations into coordinated, permission-controlled workflows.</p><p className="av-fine">Roadmap, not an available home mesh, vehicle network or autonomous control system.</p></div><div className="av-network-map" aria-label="Planned network: cameras, devices and robots supply observations to applications"><span>Cameras</span><span>Devices</span><span>Robots</span><strong>AutoVision</strong><span>Applications + human control</span></div></section>
  <section className="av-cta"><div><span className="av-kicker">START SMALL. BUILD SOMETHING BIGGER.</span><h2>Your vision. Your deployment.</h2><p>Use the hosted API or run privately in your AWS account. SmartDetector is one application. Yours can be something entirely different.</p></div><a className="av-button" href="https://aws.amazon.com/marketplace/pp/prodview-f4z2vbrqoh55u">AWS Marketplace ↗</a></section>
 </main></PublicShell>;
}
