'use client';
import {useEffect,useState} from 'react';
import {objectGroups,ObjectLabel,detectionPresets} from '@/lib/detection-catalog';
export default function ObjectDetection(){
 const [labels,setLabels]=useState<ObjectLabel[]>([]),[ready,setReady]=useState(false),[canEdit,setCanEdit]=useState(false),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[confirmation,setConfirmation]=useState('');
 useEffect(()=>{fetch('/api/v1/settings').then(async r=>{if(!r.ok)throw Error();const v=await r.json();setLabels(v.objectDetection.labels);setCanEdit(v.canEdit);setReady(true);}).catch(()=>setMessage('Could not load detection settings.'));},[]);
 async function save(){setBusy(true);try{const r=await fetch('/api/v1/settings',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({objectDetection:{labels}})});if(!r.ok)throw Error();setMessage('Detection preferences saved for this organization.');}catch{setMessage('Could not save preferences.');}finally{setBusy(false);}}
 async function purge(){setBusy(true);try{const r=await fetch('/api/v1/jobs',{method:'DELETE',headers:{'Content-Type':'application/json'},body:JSON.stringify({confirmation:'CLEAR HISTORY'})});if(!r.ok)throw Error();const v=await r.json();setMessage(`Cleared ${v.deleted} saved jobs and their previews. New analyses can continue.`);setConfirmation('');}catch{setMessage('History could not be fully cleared. Please retry.');}finally{setBusy(false);}}
 return <><section className="card g-card mb-4"><h2>Object detection</h2><p>Choose the objects your organization wants AI to look for. REST and MCP inherit this selection, or override it with <code>detection_labels</code>.</p><p className="text-secondary">OpenCV measures motion and pedestrians independently. Additional boxes use optional Bedrock AI on up to three sampled frames and are advisory—not a trained COCO detector or a safety alarm. Enable <code>classify</code> to use them. Selecting all increases prompt/output work; it does not improve accuracy.</p><div className="d-flex flex-wrap gap-2 mb-3">{Object.entries(detectionPresets).map(([name,values])=><button className="btn btn-outline-primary" disabled={!ready||!canEdit||busy} key={name} onClick={()=>setLabels([...values])}>{name==='smartdetector'?'SmartDetector defaults':name==='transport'?'Transport':'Select all'}</button>)}<button className="btn btn-outline-secondary" disabled={!ready||!canEdit||busy} onClick={()=>setLabels([])}>Clear selection</button></div><div className="row g-3">{Object.entries(objectGroups).map(([group,values])=><fieldset className="col-12 col-md-6 col-lg-4" disabled={!ready||!canEdit||busy} key={group}><legend className="h6">{group}</legend>{values.map(label=><label className="form-check" key={label}><input className="form-check-input" type="checkbox" checked={labels.includes(label)} onChange={e=>setLabels(current=>e.target.checked?[...current,label]:current.filter(v=>v!==label))}/><span className="form-check-label">{label}</span></label>)}</fieldset>)}</div><p className="mt-3">{labels.length} categories selected. Smoke and fire need representative validation; never use as a life-safety alarm.</p><button className="btn btn-primary align-self-start" disabled={!ready||!canEdit||busy} onClick={save}>Save detection preferences</button></section><section className="card g-card mb-4"><h2>Clear analysis history</h2><p>Permanently delete saved jobs, results, and sampled previews for the active organization. Users, API keys, devices, settings, and usage counters stay intact. New and in-progress analyses can still appear afterward.</p><label className="form-label" htmlFor="purge-confirmation">Type CLEAR HISTORY to confirm</label><input id="purge-confirmation" className="form-control mb-3" value={confirmation} onChange={e=>setConfirmation(e.target.value)} disabled={!canEdit||busy}/><button className="btn btn-outline-danger align-self-start" disabled={!canEdit||busy||confirmation!=='CLEAR HISTORY'} onClick={purge}>Permanently clear history</button></section><p role="status" aria-live="polite">{message}</p></>;
}
